### ISSUE TITLE
jaxen still references Codehaus

### ISSUE THREAD

**Issue by edimusrex** [archiecobbs/ivyroundup#156]
The following jar still references jaxen which went down permanently at the end of March.  Here is the url which as you can see makes the reference

http://archiecobbs.github.io/ivyroundup/repo/modules/org.codehaus.jaxen/jaxen/1.1.1/packager.xml

**Comment by archiecobbs** [comment]
Fixed in commit bb8ff68f2d32140d08917607f2a46da321f312b7.
