### ISSUE TITLE
Invalid dependency on Mockito for Powermock 1.4.10

### ISSUE THREAD

**Issue by cfinis** [archiecobbs/ivyroundup#157]
As stated on the [project page of PowerMock ](https://code.google.com/p/powermock/wiki/MockitoUsage13), PowerMock 1.4.10 requires Mockito 1.9.0-rc1 or 1.9.0. However, the ivy descriptor states "[1.8.5,)", which is wrong.
E.g. version 1.9.5 does not offer the org.mockito.internal.MockitoInvocationHandler class used by PowerMock 1.4.10.

Proposed value: "[1.9.0,1.9.5["

**Comment by archiecobbs** [comment]
Thanks... care to create a pull request?

Otherwise I'll (eventually) get to it...

**Comment by cfinis** [comment]
Sorry, I'm behind a firewall which prevents pushing to github.
The full updated dependency line is:
```xml        <dependency org="org.mockito" name="mockito" rev="[1.9.0,1.9.5[" conf="api-mockito->default"/>```

**Comment by archiecobbs** [comment]
Thanks, fixed in 7a13e8d.
