### ISSUE TITLE
Oracle JDBC 12.1.0.2 SHA-1 Values

### ISSUE THREAD

**Issue by bsoul** [archiecobbs/ivyroundup#195]
Commit 8389b8400d94956bc65a7742a1fe96a8d79a99b5 made on 7/23/16 which changes the SHA-1 values for the Oracle JDBC drivers seems incorrect.

If you go to the download page that is referenced as the home page for that version of the JDBC drivers, the SHA-1 values are listed as the old values. I even tried downloading one of them, and the old values appear to be correct.

What is the basis for this change? Is this an update Oracle made that was need released to the general public? As of right now, there is no obvious way to download the files with the hashes listed in the current packager.xml.

@noseka1

**Comment by archiecobbs** [comment]
Thanks. Not sure what happened there. Fixed in f571a49.
