### ISSUE TITLE
The asm resource site has moved?

### ISSUE THREAD

**Issue by jonathan-lord-compsci** [archiecobbs/ivyroundup#207]
I believe the resource site for asm might have changed from http://download.forge.objectweb.org to https://download.forge.ow2.org. Could you please consider updating the site? Thank you for your consideration.

http://archiecobbs.github.io/ivyroundup/repo/modules/org.objectweb.asm/asm/3.3.1/ivy.xml

**Comment by archiecobbs** [comment]
Thanks, fixed in e86255a15.
