### ISSUE TITLE
Accommodate discontinuation of GForge

### ISSUE THREAD

**Issue by jwblord** [archiecobbs/ivyroundup#219]
At least a couple packages (e.g., asm and howl) are hosted on GForge, which has apparently been discontinued (see https://www.ow2.org/view/IT_Infrastructure/GForge_discontinued). Fortunately, the projects are still available via a read-only archive, https://dllegacy.ow2.org/, so I think replacing references to http://download.forge.ow2.org/ with https://dllegacy.ow2.org/ should resolve the issue. Please let me know if you have any questions or concerns.

**Comment by archiecobbs** [comment]
Thanks for the heads-up. Should be fixed by 0438c6cc8.
